on:
  push:
    branches-ignore: master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build Step 1
        run: |
          echo "Build Step 1"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step 1
        run: |
          echo "Test Step 1"

  deploy_test_pypi:
    name: Deploy Test PyPI
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Test PyPI Step 1
        run: |
          echo "Deploy Test PyPI Step 1"
